text = 'kwypqwqykqqpqkqypukqwkpwnypykyqkywyqqypkqpkyypkpwkpwkkpypyyypywkyqpppkqppyppdpqkqywyqqeyqykykqppkpwkqpykpypwkkkyppywppywrkpoppkkkqqnpqqwpwkwpwwpykkypkwkekqpwqyykpkykoqqkqkpypkqfkqqtpyqpkppkyywyppywkpyyykwkkpyyqwyqpqkykkwppkqqpkpkkpkwkkwpwwykkyypwykwykqppyhqyqkqypyqwwqyqeoywqrpywywqpkywwkapkkkqkykkpwwwqyypqqkwwwypwkqkywqpwqqpkqkyywyqwwqwkpqykwywyyykqwyqwkwwqwqqkwyypwkwpqqpypnykpykkkwkykyppqwkkwkwyqwkqpkwpwwyppgwwwqwkqwpkyyykkkqpwkpwypewkppkkpkypqppkykqcpyykwwyhkqpkwppwkypypyqyykyakwqiwpywqkkwykykpwypwpwywqpyqqwrwqpyyqwp'

puts text.gsub(/[qwkyp]/, '')
